services:
  safed:
    build:
      context: ./
    depends_on:
      - keycloak
    environment:
      KEYCLOAK_URL: "http://keycloak:8080"
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE:-dockertest}"
      WEBHOOK_ENABLED: "${WEBHOOK_ENABLED:-false}"
      WEBHOOK_URL: "${WEBHOOK_URL:-}"
    volumes:
      - "./dev/keycloak/wait-for-keycloak.sh:/tmp/wait-for-keycloak.sh"
      - "./dev/keycloak/signing_cert.pem:/tmp/signing_cert.pem"
      - "./dev/keycloak/signing_key.pem:/tmp/signing_key.pem"
      - "./dev/example-mtls-003/src/main/resources/certs/client.key:/tmp/client.key"
      - "./dev/example-mtls-003/src/main/resources/certs/client.crt:/tmp/client.crt"
      - "./dev/example-mtls-003/src/main/resources/certs/server.crt:/tmp/server.crt"
    entrypoint: "sh -c"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: [ "/tmp/wait-for-keycloak.sh && tail -f /dev/null"]
    ports:
      - "8070:8070"
    networks: [ "safed-net" ]