server:
  port: 8070
  address: 0.0.0.0

logging:
  level:
    de.denniskniep.safed: INFO

spring:
  main:
    banner-mode: "off"
  application:
    name: safed

webhook:
  enabled: false
  url: ""
  authHeaderName: ""
  authHeaderValue: ""
